config/routes.rb
Rails.application.routes.draw do
  resource :products

  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def add_item(product_id)
    found_item = items.find { |item| item.product_id == product_id }

    if found_item
      found_item.increment
    else
      @items << CartItem.new(product_id)
    end
  end

  def empty?
    @items.empty?
  end

  def total_price
    items.reduce(0) { |sum, item| sum + item.price }
  end

  def serialize
    all_items = items.map { |item|
      { "product_id" => item.product_id, "quantity" => item.quantity}
    }

    { "items" => all_items }
  end

  def self.from_hash(hash)
    if hash.nil?
      new []
    else
      new hash["items"].map { |item_hash|
        CartItem.new(item_hash["product_id"], item_hash["quantity"])
      }
    end
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :product_id, :quantity

  def initialize(product_id, quantity = 1)
    @product_id = product_id
    @quantity = quantity
  end

  def increment(n = 1)
    @quantity += n
  end

  def product
    Product.find_by(id: product_id)
  end

  def price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include CartsHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add
    current_cart.add_tiem(params[:id])
    session[:cart9487] = current_cart.serialize

    redirect_to product_path, notice: "已加入购物车"
  end

  def destroy
    session[:cart9487] = nil
    redirect_to products_path, notice: "购物车已清空"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: "新增商品完成"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: "商品更新成功"
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find_by(id:params[:id])
    redirect_to products_path, notice: "无此商品" unless @product
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    @cart ||= Cart.from_hash(session[:cart9487])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h1>購物車</h1>

<%= link_to '清空购物车', cart_path, method::delete, class: "btn btn-default btn-danger" %>
<table class="table table-hover">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>數量</td>
      <td>單價</td>
      <td>小計</td>
    </tr>
  </thead>
  <tbody>
    <% current_cart.items.each do |item| %>
      <tr>
        <td><%= item.product.title %></td>
        <td><%= item.quantity %></td>
        <td><%= item.product.price %></td>
        <td><%= item.price %></td>
      </tr>
    <% end %>
  </tbody>
  <tfood>
  <tr>
    <td colspan="3">總計</td>
    <td><%= current_cart.total_price %></td>
  </tfood>
</table>

<%= link_to '繼續選購', products_path, class: "btn btn-default" %>
<%= link_to '結帳', '#', class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingMall</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= notice %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for product do |f| %>
  <%= f.input :title, placeholder: "商品名稱" %>
  <%= f.input :description, placeholder: "說明" %>
  <%= f.input :price, placeholder: "售價" %>
  <%= f.submit class: "btn btn-default btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<h1>編輯商品</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>商品列表</h1>

<%= link_to '新增商品', new_product_path, class: "btn btn-default btn-primary" %>
<%= link_to '购物车', cart_path, class: "btn btn-default btn-success" %>

<table class="table table-hover">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>售價</td>
      <td>處理</td>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td>
        <%= link_to '放到購物車', add_cart_path(product), method: "post", class: "btn btn-xs btn-danger" %>
        <%= product.title %>
      </td>
      <td><%= product.price %></td>
      <td>
        <%= link_to '編輯', edit_product_path(product), class: "btn btn-xs btn-default" %>
        <%= link_to '刪除', product, method: "delete", data: { confirm: "確定刪除?" }, class: "btn btn-xs btn-default" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>新增商品</h1>

<%= form_for @product do |f| %>
  名稱：<%= f.text_field :title %><br />
  說明：<%= f.text_area :description %><br />
  售價：<%= f.text_field :price %><br />
  <%= f.submit %>
<% end %>